= Eclipse Vert.x agreement proposal

== Website

The historical website of Vert.x has been available at the _vertx.io_ DNS address and hosted by a web server
managed by the Vert.x community.

This website is the official project website and remains available as it has been, the website content shall
comply to the Eclipse trademark and branding:

* The main reference of Vert.x is _Eclipse Vert.x_ (the formal project name): page title / first reference on a page.
* Footer
** The current website already displays an approved logo (from this https://www.eclipse.org/artwork/[page])
** The following links will be added in an Eclipse section
*** Main Eclipse Foundation website (http://www.eclipse.org)
*** Privacy policy (http://www.eclipse.org/legal/privacy.php)
*** Website terms of use (http://www.eclipse.org/legal/termsofuse.php)
*** Copyright agent (http://www.eclipse.org/legal/copyright.php)
*** Legal (http://www.eclipse.org/legal)

== Project development

The development of the Vert.x project will happen in a dedicated GitHub organization that will contain the
GitHub repositories of the project, the organization will likely to be named _eclipse-vertx_.

Initially this organization will contain only the vertx-core repository (currently eclipse/vertx), other projects
will be moved from the current vert-x3 organization during the migration process.

The dedicated organization is a work in progress and there is an open https://bugs.eclipse.org/bugs/show_bug.cgi?id=488119[issue]
for it.

Organization members are Eclipse committers. Current Vert.x maintainers can choose to either become an Eclipse
committer or continue to contribute via pull requests, the choice is done when the project is moved from the
vert-x3 organization to the _eclipse-vertx_ organization.

Before a project is moved under the _eclipse-vertx_ umbrella, the members can continue to contribute as usual.

The organization is administered by the Eclipse webmaster and the project lead so the project does not require intervention
of the webmaster for achieving administration tasks such as:

* Branches : define default branches, protected branches
* Webhooks & services : to integrate the repo with the CI, with Waffle, etc...
* Deploy keys

This is currently not available in Eclipse but there is an open https://bugs.eclipse.org/bugs/show_bug.cgi?id=487359[issue]
for it. Administration is agreed as stated in this https://bugs.eclipse.org/bugs/show_bug.cgi?id=488119#c19[comment].

== Naming

Vert.x continues to use the _io.vertx_ Java package name and the _io.vertx_ Maven Group Identifier.

== Versioning

Vert.x continues to the general use _major.minor.micro_ scheme with an optional qualifier for milestones,
candidate releases or hotfixes.

== Distribution

=== Repository

Vert.x has been publishing to Maven Central using the _io.vertx_ GroupId.

=== Downloads

At the moment Vert.x comes with two downloadable distributions:

* Min : a subset of the components
* Full : most Vert.x the components (for example the Ignite or JGroups cluster managers are not included)

The Vert.x distribution is a set of scripts and jar files that provides a command line interface for running Vert.x
applications. The content of the stack is dynamic, that means it is described by a descriptor file in json format
and the stack can recompute all the jars required to run this stack and pull the necessary bits from a Maven repository.

The team wants to switch the download to a dynamic download system: the download system computes an à la carte
distribution dynamically according to input parameters (i.e a list of components), there are several reasons for this:

* the number of Vert.x component grows and the full distribution becomes too big
* finer grained statistics, it is possible to know which components are popular and which are not, allowing to determine where to spend efforts and
where to not

This system should be handled by the Vert.x team. Statistics should probably made public to any committer and probably to Eclipse too.

The download page is http://vertx.io/download/ and provides:

* The vertx-base: a static distribution download that contains the base Vert.x for running polyglot (Groovy, JavaScript and Ruby) and distributed applications, equivalent more or less to the current min distribution
* The dynamic download

=== Dynamic stack

The dynamic stack provides a way to create a personalized Vert.x stack under different forms:

* custom distribution
* build file (pom.xml, etc…)
* etc...

The first iteration will only provide components of the Vert.x stack and all components are named as is as this is
the Vert.x stack.

The dynamic stack creation will be performed API server by a server managed by the Vert.x team (which does not preclude
to use a server provided by Eclipse of course). The server can use the vertx.io domain, either directly or using
a sub domain.

Later the dynamic stack will open to third-party components of the Vert.x ecosystem. The selection process will make
clear which components are _Eclipse Vert.x_ and which are not, in a similar fashion to the Eclipse IDE Marketplace.

=== Other channels

Others channels of distribution are used today by Vert.x for either Vert.x itself or some of its components of
Vert.x (for instance a Vert.x client written in Go, etc…). While Vert.x is Java centric, its polyglot nature
and its integration means software produced is consumed by other channels. The team remains  able to release
through these channels, as well as new channels that may exists in the future. Here is a list of the existing
channels used for distributing Vert.x or some of its components:

* Docker images
* NPM
* Brew
* SDKMan

There may be new channels in the future.

== Vert.x components

The Vert.x stack is a set of components forming a coherent and comprehensive stack around the vertx-core project
(eclipse/vertx repository). A few components are consumed by the core as dependencies, such as the code generation,
but most of them are depending on the core.

=== Eclipse retrofit

The components of the Vert.x stack will be migrated in several steps under the _Eclipse Vert.x_ project.
There is no definite schedule for this yet, however the order of migration will follow the project
dependencies, for example the _vertx-core_ dependencies will be migrated first, then the _vertx-lang-*_, etc…
The maintainers agree on the order of migration and the schedule.

Component migration will likely involve the creation of a Contribution Questionnaire and involve an IP check of the source tree.
Each component repository is transferred from the vert-x3 organization to the _eclipse-vertx_ organization.


The maintainers of a component should become _Eclipse Vert.x_ committers or a new maintainer will be named and
contributions will happen via _signed-off_ pull requests.

Components that won’t be retrofitted (for example obsolete components) will be kept as is, as they can
still be consumed but no development happens, beside bug fixes (such as security patch).

The component licensing is to take these projects under ASL, then add a prominent notice in the readme that state
that before the migration date, the component is under ASL and after it is under the ASL/EPL license.

=== Component naming

The actual components keep their current name either because they will be migrated or because they will be
retired, in which case they will not be active anymore.

=== Extra components

There are Vert.x project outside of the Vert.x stack:

* A project being incubated and not yet releasable
* A project removed of the stack for some reason
* A project that does not have sense to be there (for instance the Vert.x example projects that is a repository of examples)

Projects should either by in the _eclipse-vertx_ repository or in another repository like _vertx-labs_.

== New components

New components are developed developed in _Eclipse Vert.x_, either in the _eclipse-vertx_ organization or in the
_vertx-labs_ organization.
